[project]
name = "comfyui-uv-linux-nvidia-gpu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "packaging>=26.0",
    "requests>=2.32.5",
    "typer>=0.21.1",
]
